// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiIk0TyVdmpu1IEiQroFjnN3pPVSJl6K0',
    appId: '1:921368196746:android:d47a8e1d3cd015a0cf5f73',
    messagingSenderId: '921368196746',
    projectId: 'nktt-f7264',
    databaseURL: 'https://nktt-f7264-default-rtdb.firebaseio.com',
    storageBucket: 'nktt-f7264.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw7ri5Q2QaIxmCXWoWPInuCJ5MnYNY244',
    appId: '1:921368196746:ios:e07f70b229b099b4cf5f73',
    messagingSenderId: '921368196746',
    projectId: 'nktt-f7264',
    databaseURL: 'https://nktt-f7264-default-rtdb.firebaseio.com',
    storageBucket: 'nktt-f7264.firebasestorage.app',
    iosBundleId: 'com.example.nhatKyTrongTrot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd97yl5C_VMa5bxjxrQiyxhzg5q6tj-UA',
    appId: '1:921368196746:web:4a2f3bcc92c0b58ecf5f73',
    messagingSenderId: '921368196746',
    projectId: 'nktt-f7264',
    authDomain: 'nktt-f7264.firebaseapp.com',
    databaseURL: 'https://nktt-f7264-default-rtdb.firebaseio.com',
    storageBucket: 'nktt-f7264.firebasestorage.app',
    measurementId: 'G-44PZJR16VH',
  );

}